name: Run Message Test

on:
  push:
    branches: [ main ]

jobs:
  send-msg-test:
    name: Send Message Test
    runs-on: ubuntu-20.04
    steps:
      - name: Send message to slack channel
        id: notify
        if: always()
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: C03T6JKLJSH
          slack-text: Test message sending from github workflow.
      
      - name: Result from "Send Message to slack channel"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
